// Central icon set for the app. Single source so the iconography stays
// consistent (monochrome, stroke-based lucide icons that inherit currentColor).
// Import from here rather than reaching into lucide-react directly.
export {
  LayoutDashboard,
  Luggage,
  Bell,
  CircleHelp,
  Settings,
  Plane,
  MapPin,
  Map as MapIcon,
  Hotel,
  Users,
  UserPlus,
  User,
  ListChecks,
  ClipboardList,
  Wallet,
  CalendarDays,
  History,
  Clock,
  AlarmClock,
  Trash2,
  TriangleAlert,
  StickyNote,
  Pencil,
  Plus,
  X,
  Check,
  ChevronDown,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ExternalLink,
  Search,
  Share2,
  Copy,
  Repeat,
  Power,
  Menu,
  LogIn,
  Mail,
  Phone,
  KeyRound,
  ShieldCheck,
  DoorOpen,
  Route as RouteIcon,
  Star,
  Globe,
  Rocket,
  Compass,
  Monitor,
  Sun,
  Moon,
  Palette,
  Loader2,
  PlaneTakeoff,
  PlaneLanding,
  Crown,
  type LucideIcon,
} from "lucide-react";
